### PR TITLE
Clarify that payload and descr are optional

### PR DESCRIPTION
**Pull request by singpolyma**

### CODE REVIEW

**Comment by iequidoo** [comment]
> for `descr`, i think, we should even remove it completely.

I also think so, there's even no way to reliably set a description for a particular update, just the last description is used for a batch of updates, dropping the previously set description. Probably can be fixed by appending the existing descrition, but just dropping is also fine

**Comment by singpolyma** [comment]
What reason would there be to require putting a `null` payload? Other than deltachat current assumes this I understand, but surely this can be changed without too much disruption?  It can be useful for a WebXDC to send a message to the chat without any accompanying state update. Obviously some messages will have a payload, but why require it for all of them?

**Comment by adbenitez** [comment]
there is no technical reason that requires payload to be set, the only reason (as I think @r10s already explained) is so it is harder for developers to do a mistake and don't put a payload, it is not important that it is enforced 99% of all status updates will need it, only some rare cases would not need a payload, the main use case of status updates is to share **status updates** with the other devices, sending an status update without a payload is a corner case for some half-implemented apps or apps that only want to display a cosmetic message in the chat without really sending an status update, it is not worthy to change the rules for the exception use case

**Comment by hpk42** [comment]
the "descr" is gone via #92 now (which was only merged into next-main). 

As to allowing "payload" to be left undefined the main argument is that there would be no required argument at all and `sendUpdate({})` would be a valid invocation according to the spec which looks a bit useless.  By at least requiring `payload` to be specified, even as `null` it nudges the developer to think about it and not make practically useless calls without any arguments. 
@singpolyma, can you live with leaving the `payload` to be a required key? 
We can then close this PR.

**Pull request closed without merging**
