### PR TITLE
Specify message size limits

### PR DESCRIPTION
**Pull request by singpolyma**
To facilitate portable interaction with size-limited protocols.

### CODE REVIEW

**Comment by hpk42** [comment]
I suspect there are size-limits for XMPP here? Could you point to them?

**Comment by singpolyma** [comment]
You can see some information about common XMPP size limits for example in https://prosody.im/security/advisory_20210512/

**Comment by hpk42** [comment]
Hello @singpolyma -- not sure you are still seeing the webxdc-collab chat (bridge might be broken).  What do you think about specifying the limits in a `ratelimits` object? https://github.com/webxdc/website/pull/91/files#diff-2fcd88b9566b3500d43cfddf674778e949219dcb4ea1397b62bbb41ae118cb37R17

For realtime, i think it's fine to limit it to 128kb fixed in the spec text -- but regular updates might have different maximum sizes, and the messaging layer should be able to provide them. 
Or is it also true that XMPP would not accept any incoming update size larger than 128kb?

**Comment by singpolyma** [comment]
>For realtime, i think it's fine to limit it to 128kb fixed in the spec text 
>-- but regular updates might have different maximum sizes, and the 
>messaging layer should be able to provide them.
>Or is it also true that XMPP would not accept any incoming update size
>larger than 128kb?

Yeah it'll be ~128kb across the board for us

**Comment by singpolyma** [comment]
>But I cannot find 128 KB there, is it actually specified somewhere in RFC 
>or where does it come from?

There is no standard size but 128kb is a safe size to fit in all default 
size limits of common servers.

-- 
Stephen Paul Weber, @singpolyma
See <http://singpolyma.net> for how I prefer to be contacted
edition right joseph

**Comment by hpk42** [comment]
@Singpolyma, could you check if https://github.com/webxdc/website/pull/91 fits for xmpp purposes?  WE took over the absolute limit of 128000 for realtime updates but introduce `sendUpdateMaxSize` and `sendUpdateInterval` see the PR.

**Comment by singpolyma** [comment]
#91 seems fine

**Pull request closed without merging**
