### PR TITLE
Additional improvements to the app listing

### PR DESCRIPTION
**Pull request by jagtalon**
This should fix the issues:

- Wrong icons appearing when changing categories / filtering
- Adding author instead of "Updated to ..."
- Update the icons to more accurate analogs like a gamepad and a calendar

### CODE REVIEW

**Comment by jagtalon** [comment]
I was chatting with Xenia and I wanted to add one last change. Since we're not prominently showing "Updated to ..." anymore, the default sorting is now alphabetical.

Is that good with you all? @hpk42 @adbenitez @r10s?

**Comment by hpk42** [comment]
dunno but  i'd keep the last-updated order.  It's true that it's now unclear how apps are sorted. Then again, people know from gplay/applestore that that ranking is a bit arbitrary.

**Comment by r10s** [comment]
agree, to sum up discussions, it was regarded to be better to stay with recently-added-ordering:

> alphabetical order will make it hard to spot new added apps to try or updated ones
>
> things will easily feel "stale" as esp. the first apps of the store virtually never change
> 
> it is true, that the sort criterion is not visible, however, this is true for many other comparable lists,
> and regarded as being fine.
> ppl won't wonder.

**Comment by jagtalon** [comment]
@r10s @hpk42 makes sense esp with the app feeling stale. I'll revert and merge if everything else is good!

**Review by hpk42 — APPROVED** [review]
sounds good. Maybe again squash-merge so it's easy to revert if it causes problems for cheogram or monocles.

**Comment by jagtalon** [comment]
Squashed!

**Pull request merged**
